### ISSUE TITLE
Non-valid XLIFF 1.2 instance

### ISSUE THREAD

**Issue by Soroush-sdf** [w3c/its-2.0-testsuite#33]
In the Example1_XML.xml.xlf the note element (line 22) appears after non-xliff elements which is not allowed by the XLIFF 1.2 spec.
https://github.com/w3c/its-2.0-testsuite/blob/master/its2.0/xliffsamples/Example1_XML.xml.xlf

Thanks.

**Comment by fsasaki** [comment]
Thanks, @Soroush-sdf . Can you open a pull request for this issue and for https://github.com/w3c/its-2.0-testsuite/issues/32 to get them fixed?
